src/iEPM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', home , name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^organizations/', include("organizations.urls", namespace="organizations")),
    url(r'^permissions/', include("permissions.urls", namespace="permissions")),
    url(r'^posts/', include("posts.urls", namespace="posts")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
# from django.urls import path
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'', addNewPost, name='add-new-post'),
]

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}iEPM {% endblock %}</title>
  {% include 'snippets/css/css.html' %}
</head>

<div class="container">

<body>
  {% include 'snippets/nav.html' %}
  <br>
  {% block nav %}

  {% endblock nav %}

  <main>
      {% block content %}
      {% endblock %}
  </main>
</body>
</div>

{% include 'snippets/js/js.html' %}
{% block js %}
{% endblock js %}

</html>

src/templates/create.html
{% extends 'base.html'%}
{% block content %}
<form method="post" enctype='multipart/form-data'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

src/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>home</h1>
<br>
<div class="container">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
    Add Post</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Posts</h4>
        </div>
<!-- form -->
        <form class="" action="{% url 'posts:add-new-post' %}" method="POST" id="post-form">
          {% csrf_token %}
          <div class="modal-body">
            <input type="text" name="title" id="title-id" value="" placeholder="title"><hr>
            <textarea name="body" id="body-id" rows="8" cols="60" placeholder="Post Body" required></textarea>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-info">Add again</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          </div>
      </form>
<!-- /form -->
      </div>
    </div>
  </div>
</div><br><br><br>

<div class="" id = "post-id">

</div>
{% if posts.count %}
{% for post in posts %}
<div class="well" >
  <div class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="http://placekitten.com/150/150"></a>
      <div class="media-body">
        <h4 class="media-heading">{{post.title}}</h4>
          <p class="text-right">By Francisco</p>
          <p>{{post.body}} </p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> {{post.updated_at|timesince }} ago </span></li>
            <li>|</li><span><i class="glyphicon glyphicon-comment"></i> 2 comments</span>
            <li>|</li>
            <li>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            <li>|</li>
            <li></li>
          </ul>
      </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

{% block js %}
<script type="text/javascript">
  $('#post-form').on('submit', function(event){
      event.preventDefault();
      console.log("form submitted!")
      create_post();
  });

  function create_post() {
    console.log("create post is working!")
    var token = $("#post-form").find('input[name=csrfmiddlewaretoken]').val()
    $.ajax({
        url : "{% url 'posts:add-new-post' %}",
        type : "POST",
        data : {
          title : $('#title-id').val(),
          body  : $('#body-id').val() ,
          csrfmiddlewaretoken : token,
         },

        success : function(json) {
            $('#title-id').val('');
            $('#body-id').val('');
            console.log(json.updated_at);
            $("#post-id").prepend('<div class="well" >' +
              '<div class="media"><a class="pull-left" href="#">'+
              '<img class="media-object" src="http://placekitten.com/150/150"></a>'+
              '<div class="media-body"><h4 class="media-heading">'+json.title+'</h4>'+
              '<p class="text-right">By Francisco</p><p>'+json.body+'</p>'+
              '<ul class="list-inline list-unstyled">'+
              '<li><span><i class="glyphicon glyphicon-calendar"></i>'+json.updated_at+'</span></li>'+
              '<li>|</li><span><i class="glyphicon glyphicon-comment"></i> 2 comments</span>'+
              '<li>|</li><li><span class="glyphicon glyphicon-star"></span>'+
              '<span class="glyphicon glyphicon-star"></span>'+
              '<span class="glyphicon glyphicon-star"></span>'+
              '<span class="glyphicon glyphicon-star"></span>'+
              '<span class="glyphicon glyphicon-star-empty"></span>'+
              '</li><li>|</li><li></li></ul></div></div></div>');
            console.log("success");
        },

        error : function(xhr,errmsg,err) {
            console.log("error");

        }
    });
};
</script>
{% endblock js %}

src/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>
{% endblock %}