src/iEPM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', home , name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^organizations/', include("organizations.urls", namespace="organizations")),
    url(r'^permissions/', include("permissions.urls", namespace="permissions")),
    url(r'^posts/', include("posts.urls", namespace="posts")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/permissions/urls.py
# from django.urls import path
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/create-permissions/$' ,  createPermissions ,name="create-permissions" ) ,
    url(r'^(?P<pk>\d+)/edit/$' ,  editPermissions ,name="edit-permissions" ) ,
]

src/permissions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/permissions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from users.models import CustomUser
from django.urls import reverse


"""
only super user who can create new permission
"""
def isSuperuser(user):
    return True if user.is_superuser else False

@user_passes_test(isSuperuser , login_url = 'users:login')
def createPermissions(request, slug):
    if request.method == "POST":
        instance = request.POST
        code_name = instance["code_name"]
        name = instance["name"]
        # instance.save()
        ct = ContentType.objects.get_for_model(CustomUser) # @permission_required("users.can_view_organization_user")
        permission = Permission.objects.create(
        codename=str(code_name),
        name=str(name),
        content_type = ct
        )
        request.user.user_permissions.add(permission)
        return redirect(reverse("permissions:create-permissions" , kwargs= {"slug" :slug }))
    else:
        permissions= request.user.user_permissions.all()
    context = {
    "permissions" : permissions ,
    }
    return render(request, "permissions/create_permissions.html", context)

"""
only super user who can edit permission 
"""
@user_passes_test(isSuperuser , login_url = 'users:login')
def editPermissions(request, pk):
    if request.method == "POST":
        perm = Permission.objects.get(id= pk)
        perm.delete()
        instance = request.POST
        code_name = instance["code_name"]
        name = instance["name"]
        print(code_name, name)
        ct = ContentType.objects.get_for_model(CustomUser)
        permission = Permission.objects.create(
        codename=str(code_name),
        name=str(name),
        content_type = ct
        )
        request.user.user_permissions.add(permission)
        # return redirect(reverse("permissions:create-permissions" , kwargs= {"slug" :slug }))
        return redirect("/")
    perm = Permission.objects.get(id= pk)
    context= {
    "permission"  : perm
        }
    return render(request, "permissions/edit.html", context)

src/permissions/templates/permissions/create_permissions.html
{% extends 'base.html' %}
{% block title %} Organization | {{block.super}} {% endblock %}
{% block content %}
<h1>Permission</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code Name</th>
    <th>Code</th>
    <th>Edit</th>
  </tr>
  {% for perm in permissions %}
  <tr>
    <td>{{perm.name}}</td>
    <td>{{perm.codename}}</td>
    <td>{{perm}}</td>
    <td><a href="{% url 'permissions:edit-permissions' perm.id %}">
        <button type="button" name="button">Edit</button></a>
    </td>
  </tr>
  {% endfor %}
</table><br><hr><br>
<form method="post">
  {% csrf_token %}
  <div>
    <label for="code_name">Add Permission Code :</label>
    <input type="text" id="code_name" name="code_name" value="" placeholder="e.g: can_add_user {Unique}  "><br><br>
    <label for="name">Add Permission Name :</label>
    <input type="text" id="name" name="name" value="" placeholder="e.g: This User Can Add Users">
  </div><br>
  <button type="submit">Save</button>
</form>
<br>
{% endblock %}

src/permissions/templates/permissions/edit.html
{% extends 'base.html' %}
{% block title %} Organization | {{block.super}} {% endblock %}
{% block content %}
<br>{{permission}}
<br>
<form method="post">
  {% csrf_token %}
<br>
  <div>

    <label for="code_name">Edit Permission Code :</label>
    <input type="text"
    id="code_name" name="code_name"
    value="{{permission.codename}}"><br><br>

    <label for="name">Edit Permission Name :</label>
    <input type="text"
    id="name" name="name"
    value="{{permission.name}}" >
  </div><br>
  
  <button type="submit">Save</button>
</form>
{% endblock %}