src/iEPM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', home , name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^organizations/', include("organizations.urls", namespace="organizations")),
    url(r'^permissions/', include("permissions.urls", namespace="permissions")),
    url(r'^posts/', include("posts.urls", namespace="posts")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/organizations/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^create/$' ,  organizationsCreate ,name="create" ) ,
    url(r'^organization/$' ,  myOrganizationsList ,name="myorganizations-list" ) ,
    url(r'^myadmin/organization-list/$', organizationsList , name='organizations-list'), # Admin
    url(r'^(?P<slug>[-\w]+)/detail/$', organizationDetail ,name="organizations-detail"),
    url(r'^(?P<slug>[-\w]+)/update/$', OrganizationsUpdateView.as_view(),name="update"),

    ]

src/users/urls.py
# from django.urls import path
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'signup/', mySignup, name='signup'),
    url(r'login/', myLogin, name='login'),
    url(r'^myadmin/users-list/', users_list, name='users-list'),
    url(r'myadmin/', myadmin, name='myadmin'),

    url(r'^(?P<slug>[-\w]+)/create-organization-user/$' ,  createOrganizationUser ,name="create-organization-user" ) ,

    url(r'^(?P<pk>\d+)/edit-permissions', userEditPermissions , name='edit-permissions'),
    url(r'^(?P<pk>\d+)/profile/', profile, name='profile'),
]

src/templates/snippets/nav.html
<a href="{% url 'home' %}">Home</a>

{% if request.user.is_authenticated %}
    <br><a href="{% url 'logout' %}"> Logout </a><hr><br>
    {% if request.user.profile_picture %}
          <a target="_blank" href="{{request.user.profile_picture.url}}">
            <img src="{{ request.user.profile_picture.url }}" alt="Avatar" class="avatar">
          </a>
    {% else %}
          <img src="{{ MEDIA_URL }}Profile_pictures/anonymous.jpg" alt="Avatar" class="avatar">
    {% endif %}
    <div class="">
      <a href="{% url 'users:profile' user.pk %}"> <b>{{request.user}}</b></a>
    </div>

    {% if request.user.is_superuser and request.user.is_staff  %}
          <p >logged as <b style="color:red">Super</b> User</p>
          <br>
          <a href="{% url 'users:myadmin' %}"> SuperAdmin </a>,
          <b style="color:red">NOTE : </b><small >Admin is Available to
          <b style="color:green">Staff</b>  and <b style="color:red">Super</b> Users only. </small>
    {% elif request.user.is_staff %}
          <p>logged as <b style="color:green">Staff </b>User</p>
          <br><a href="{% url 'users:myadmin' %}"> Admin </a>
          <small >Admin is Available to
          <b style="color:green">Staff</b>  and <b style="color:red">Super</b> Users only </small>
    {% else %}
          <p >logged as <b style="color:orange">Standard</b> User</p>
    {% endif %}
    <hr>
    Organization :
    <a href="{% url 'organizations:myorganizations-list' %}">Organization</a>
    {% if request.user.organization == None %}
      <a href="{% url 'organizations:create' %}">Create New</a>
        <small>
       You can create organization because you are not a member of any organization .</small>
   {% endif %}
{% else %}
    <br><a href="{% url 'users:login' %}"> Log In </a>|
    <a href="{% url 'users:signup' %}">signup</a>
{% endif %}
<hr>