src/iEPM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', home , name='home'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^organizations/', include("organizations.urls", namespace="organizations")),
    url(r'^permissions/', include("permissions.urls", namespace="permissions")),
    url(r'^posts/', include("posts.urls", namespace="posts")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/organizations/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^create/$' ,  organizationsCreate ,name="create" ) ,
    url(r'^organization/$' ,  myOrganizationsList ,name="myorganizations-list" ) ,
    url(r'^myadmin/organization-list/$', organizationsList , name='organizations-list'), # Admin
    url(r'^(?P<slug>[-\w]+)/detail/$', organizationDetail ,name="organizations-detail"),
    url(r'^(?P<slug>[-\w]+)/update/$', OrganizationsUpdateView.as_view(),name="update"),

    ]

src/permissions/urls.py
# from django.urls import path
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/create-permissions/$' ,  createPermissions ,name="create-permissions" ) ,
    url(r'^(?P<pk>\d+)/edit/$' ,  editPermissions ,name="edit-permissions" ) ,
]

src/users/urls.py
# from django.urls import path
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'signup/', mySignup, name='signup'),
    url(r'login/', myLogin, name='login'),
    url(r'^myadmin/users-list/', users_list, name='users-list'),
    url(r'myadmin/', myadmin, name='myadmin'),

    url(r'^(?P<slug>[-\w]+)/create-organization-user/$' ,  createOrganizationUser ,name="create-organization-user" ) ,

    url(r'^(?P<pk>\d+)/edit-permissions', userEditPermissions , name='edit-permissions'),
    url(r'^(?P<pk>\d+)/profile/', profile, name='profile'),
]

src/organizations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser

from django.db import models
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.urls import reverse
import random


def file_upload_location(instance, filename):
    return "Auth_pictures/{}/{}".format(instance.name, filename)
def image_upload_location(instance, filename):
    return "Profile_pictures/{}/{}".format(instance.name, filename)
    
class Organization(models.Model):
    owner_id    = models.IntegerField(default = 1)
    name        = models.CharField(max_length=30, blank=True)
    bio         = models.TextField(max_length=500, blank=True)
    location    = models.CharField(max_length=30, blank=True)
    logo        = models.FileField(upload_to = image_upload_location,
                                      null=True,
                                      blank=True,)
    auth_image  = models.FileField(upload_to = file_upload_location,
                                      null=True,
                                      blank=True,
                                      help_text= "Add Your Authorization Pdf")
    slug        = models.SlugField(null=True , blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("organizations:organizations-detail" , kwargs={"slug" : self.slug})

def pre_save_organization(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug  = slugify(instance.name)+'-'+str(random.randint(1,1000000000))
pre_save.connect(pre_save_organization, Organization)

src/permissions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/organizations/forms.py
from django import forms
from users.forms import CustomUserCreateForm
from users.models import CustomUser
from .models import Organization

class DateInput(forms.DateInput):
    input_type = 'date'
class OrganizationUserCreateForm(CustomUserCreateForm):
    class Meta:
        model = CustomUser
        fields = [
            # "organization",
            'username',
            'email',
            'profile_picture',
            'birth_date',
            'bio',
        ]
        widgets = {
                    'birth_date': DateInput()
                }

class OrganizationCreateForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = [
        # "owner_id",
        "name",
        "bio",
        "location",
        "auth_image",
        "logo"
        ]
class OrganizationUpdateForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = [
        # "owner_id",
        "name",
        "bio",
        "location",
        "logo"
        # "auth_image",
        ]

src/organizations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .forms import OrganizationUserCreateForm, OrganizationCreateForm, OrganizationUpdateForm
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from users.models import CustomUser
from .models import Organization
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import permission_required, user_passes_test

"""
# user who don't belong to any organizations only who can create a new organization
# assign the organization to the owner user
# set is_owner value to True
"""
def organizationsCreate(request):
    if request.user.organization == None :
        user_id = request.user.id
        user = CustomUser.objects.get(id = user_id)
        if request.method == "POST":
            form = OrganizationCreateForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.owner_id = int(request.user.id)
                instance.save()
                all_permissions =  Permission.objects.filter(codename__contains="organization")
                print(all_permissions)
                user.user_permissions.set(all_permissions)
                user.organization = instance
                user.is_owner = True
                user.save()
                return redirect(reverse('home'))
                # return redirect(reverse('organizations:myorganizations-list'))
        else :
            form = OrganizationCreateForm()
        context = {
        "form" : form ,
        }
        return render(request, "create.html",context)
    else:
        return HttpResponse("<script>alert('You can not add new Organization Because you are a member in {} organization');</script>".format(request.user.organization))

"""
My Organization
# not very important because user have only one organization so
# it can show the detail view directly
"""
def myOrganizationsList(request):
    user_organization = request.user.organization
    user_role = ''
    if user_organization :
        if user_organization.owner_id == request.user.id:
            user_role = 'You are The Owner Of that Organization'
        else :
            user_role = 'You are a Member of that Organization '

    context = {
    "organization" : user_organization,
    "user_role" :user_role
    }
    return render(request, "organizations/organizations-list.html", context)

"""
show all organizations for the staff users "is_satff or is_superuser"
"""
def isStaff(user):
    return True if user.is_staff or user.is_superuser else False

@user_passes_test(isStaff , login_url = 'users:login')
def organizationsList(request):
    organizations = Organization.objects.all()
    context = {
    "organizations" : organizations,
    }
    return render(request, "organizations/admin-organizations-list.html", context)

"""
show organization details
"""
def organizationDetail(request, slug):
    organization        = Organization.objects.get(slug= slug)
    user_id             = organization.owner_id
    user                = CustomUser.objects.get(id = user_id)
    organization_users  = organization.users.all()
    user_role = ''
    if request.user.organization != None :
        if request.user.organization.owner_id == request.user.id :
            user_role = 'You are The Owner Of that Organization'
        else :
            user_role = 'You are a Member of that Page '
    context      = {
    "user"               : user,
    "organization_users" : organization_users,
    "organization"       : organization,
    "user_role"          : user_role,
    }
    return render(request, "organizations/organizations-detail.html", context)

"""
update the organiztion
"""
class OrganizationsUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    permission_required = 'users.change_organization'
    form_class = OrganizationUpdateForm
    template_name = "create.html"
    queryset = Organization.objects.all()

src/permissions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from users.models import CustomUser
from django.urls import reverse


"""
only super user who can create new permission
"""
def isSuperuser(user):
    return True if user.is_superuser else False

@user_passes_test(isSuperuser , login_url = 'users:login')
def createPermissions(request, slug):
    if request.method == "POST":
        instance = request.POST
        code_name = instance["code_name"]
        name = instance["name"]
        # instance.save()
        ct = ContentType.objects.get_for_model(CustomUser) # @permission_required("users.can_view_organization_user")
        permission = Permission.objects.create(
        codename=str(code_name),
        name=str(name),
        content_type = ct
        )
        request.user.user_permissions.add(permission)
        return redirect(reverse("permissions:create-permissions" , kwargs= {"slug" :slug }))
    else:
        permissions= request.user.user_permissions.all()
    context = {
    "permissions" : permissions ,
    }
    return render(request, "permissions/create_permissions.html", context)

"""
only super user who can edit permission 
"""
@user_passes_test(isSuperuser , login_url = 'users:login')
def editPermissions(request, pk):
    if request.method == "POST":
        perm = Permission.objects.get(id= pk)
        perm.delete()
        instance = request.POST
        code_name = instance["code_name"]
        name = instance["name"]
        print(code_name, name)
        ct = ContentType.objects.get_for_model(CustomUser)
        permission = Permission.objects.create(
        codename=str(code_name),
        name=str(name),
        content_type = ct
        )
        request.user.user_permissions.add(permission)
        # return redirect(reverse("permissions:create-permissions" , kwargs= {"slug" :slug }))
        return redirect("/")
    perm = Permission.objects.get(id= pk)
    context= {
    "permission"  : perm
        }
    return render(request, "permissions/edit.html", context)

src/organizations/templates/organizations/admin-organizations-list.html
{% extends 'base.html'%}
{% block content %}

{% if organizations %}
<h2>{{user_role}}</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Bio</th>
  </tr>
  {% for organization in organizations %}
  <tr>
    <td>
      <a href="{% url 'organizations:organizations-detail' organization.slug %}">
          {% if organization.logo %}
              <img src="{{organization.logo.url}}" alt="Avatar" class="avatar">
          {% else %}
              <img src="{{ MEDIA_URL }}Profile_pictures/anonymous.jpg" alt="Avatar" class="avatar">
          {% endif %}
              {{organization}}
      </a>
    </td>
    <td>{{organization.location}}</td>
    <td>{{organization.bio}}</td>
  </tr>
{% endfor %}

</table>
{% else %}
YOU ARE NOT A MEMBER Or OWNER OF ANY ORGANIZATION </b>
{% endif %}
{% endblock %}

src/organizations/templates/organizations/organizations-detail.html
{% extends 'base.html' %}
{% block title %} Organization | {{block.super}} {% endblock %}
{% block content %}
<h2>{{user_role}}</h2>
<p><b>Owner : </b>{{user}}</p>


{% if organization.logo %}
<a target="_blank" href="{{organization.logo.url}}">
  <img src="{{organization.logo.url}}" alt="Forest" style="width:500px">
</a><br>
{% else %}
<img src="{{ MEDIA_URL }}Profile_pictures/anonymous.jpg" alt="Avatar" class="avatar">
{% endif %}
{% if organization.auth_image %}
<a href="{{organization.auth_image.url}}"> Authorization PDF</a>
{% endif %}
<br>
<h1>{{organization.name}}</h1><b>location: </b><small>{{organization.location}}</small>
<p><b>Bio : </b> {{organization.bio}} </p>
<!--  -->
<hr>
{% if organization_users.count %}
<h2>{{organization}} users</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Edit Permissions</th>
  </tr>
  {% for user in organization_users %}
  <tr>
    <td>
      <a href="{% url 'users:profile' user.pk %}">
          {% if user.profile_picture %}
              <img src="{{user.profile_picture.url}}" alt="Avatar" class="avatar">
          {% else %}
              <img src="{{ MEDIA_URL }}Profile_pictures/anonymous.jpg" alt="Avatar" class="avatar">
          {% endif %}
      {{user}}
      </a>
    </td>
    <td>
      {% if not user.is_owner %}
      <a href="{% url 'users:edit-permissions' user.pk %}">
        <button type="button" name="button">Edit</button></a>
        {% endif %}
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p > Organization have no users yet .
  <a href="{% url 'users:create-organization-user' organization.slug %} ">add users</a> </p>
{% endif %}
<p><a href="{% url 'users:create-organization-user' organization.slug %}">
  <b>Add New User</b></a></p>

<p><a href="{% url 'permissions:create-permissions' organization.slug %}">
  <b>Permissions</b> </a></p>
<!--  --><br>
<a href="{% url 'organizations:update' organization.slug %}"><button type="button" name="button">Update</button></a>

{% endblock %}

src/organizations/templates/organizations/organizations-list.html
{% extends 'base.html'%}
{% block content %}

{% if organization %}
<h2>{{user_role}}</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Bio</th>
  </tr>

  <tr>
    <td>
      <a href="{% url 'organizations:organizations-detail' organization.slug %}">
          {% if organization.logo %}
              <img src="{{organization.logo.url}}" alt="Avatar" class="avatar">
          {% else %}
              <img src="{{ MEDIA_URL }}Profile_pictures/anonymous.jpg" alt="Avatar" class="avatar">
          {% endif %}
              {{organization}}
      </a>
    </td>
    <td>{{organization.location}}</td>
    <td>{{organization.bio}}</td>
  </tr>


</table>
{% else %}
YOU ARE NOT A MEMBER Or OWNER OF ANY ORGANIZATION </b>
{% endif %}
{% endblock %}

src/organizations/templates/organizations/permissions.html
{% extends 'base.html' %}
{% block title %} Organization | {{block.super}} {% endblock %}
{% block content %}
<h1>Permission</h1>
<form method="post">
  {% csrf_token %}
  <div>
    {% for perm in permissions%}
    <input type="checkbox" id="subscribeNews" name="checks" value="{{perm}}">
    <label for="subscribeNews">{{perm.name}}</label><br>
    {% endfor %}
  </div><br>
  <button type="submit">Save</button>
</form>
{% endblock %}